config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # root to: 'pictures#user_feed'
  root to: 'pages#home'

  resources :users, only: [:index]

  resources :chatrooms, only: [:create, :show, :index] do
    resources :messages, only: :create
  end

  resources :pictures, only: [:new, :create, :destroy]
  resources :collaborations
  get '/feed', to: 'pictures#user_feed', as: "feed"
  get '/:username', to: 'pictures#user_gallery', as: "gallery"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<% flash.each do |key, value| %>
  <div>
    <%= value %>
  </div>
<% end %>
<% if user_signed_in? %>
  <p>Signed in as <%= current_user.name %> | <%= link_to 'log out', destroy_user_session_path, method: :delete %></p>
<% end %>
<ul>
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'Users', users_path %></li>
</ul>

app/views/shared/_navbar.html.erb
<div class="container">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to feed_path, class: "navbar-brand" do %>
        <div class="text-logo">Photocycle</div>
      <% end %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "My gallery", gallery_path(current_user.username), class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "+Add photo", new_picture_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Messages", chatrooms_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Collabs", collaborations_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Favourites", "#", class: "dropdown-item" %>
                <%= link_to "Account settings", "#", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
  </div>
</div>

app/views/shared/_navbar_home.html.erb
<div class="navbar-lewagon-home">
  <div class="container">
    <div class="navbar navbar-expand-sm navbar-light">
        <%= link_to feed_path, class: "navbar-brand" do %>
          <div class="text-logo-home">Photocycle</div>
        <% end %>
    </div>
  </div>
</div>