config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # root to: 'pictures#user_feed'
  root to: 'pages#home'

  resources :users, only: [:index]

  resources :chatrooms, only: [:create, :show, :index] do
    resources :messages, only: :create
  end

  resources :pictures, only: [:new, :create, :destroy]
  resources :collaborations
  get '/feed', to: 'pictures#user_feed', as: "feed"
  get '/:username', to: 'pictures#user_gallery', as: "gallery"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  belongs_to :collaboration, optional: true
  has_one_attached :photo, dependent: :destroy
  has_many :photo_categories, dependent: :destroy
  has_many :categories, through: :photo_categories
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def user_gallery
    @user = User.find_by(username: params[:username])
    @users = User.all
    #(current_user)
    @chatroom = Chatroom.new

    @single_chatroom = Chatroom.find_by(first_user: current_user, second_user: @user) ||
                       Chatroom.find_by(first_user: @user, second_user: current_user) ||
                       Chatroom.create_private_chatroom(@user, current_user)
    @message= Message.new
    @messages = @single_chatroom.messages.order(created_at: :asc) if @single_chatroom
    @user_pictures = Picture.where(user: @user).where(collaboration_id: nil)
    @user_categories = []
    @user_pictures.each do |pic|
      pic.categories.each do |category|
        @user_categories.push(category.name)
      end
    end
    @user_categories.uniq!
    user_collabs = Collaboration.where(["artist1_id = ? or artist2_id = ?", @user.id, @user.id]).where(status: 1)
    @user_collab_pictures = Picture.where(collaboration: user_collabs)
    # defining a picture variable for the 'Add photo' modal
    @picture = Picture.new
    # defining a collab variable for the 'Propose collab' modal
    @collab = Collaboration.new
  end

  def user_feed
    @pictures = Picture.all.includes(photo_categories: :category)
    if params[:query]
      @pictures = @pictures.joins(:photo_categories, :categories).where('categories.name ILIKE ?', "%#{params[:query]}%").distinct
    end
    respond_to do |format|
      format.text { render partial: 'pictures/user_feed_photos', locals: { pictures: @pictures }, formats: [:html] }
      format.html
    end
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user = current_user
    if @picture.save
      redirect_to gallery_path(current_user.username)
    else
      render :new
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to gallery_path(current_user.username)
  end

  private

  def get_name(user1, user2)
    user = [user1, user2]
    "conversation privée_#{user[0].id}_#{user[1].id},"
  end

  def picture_params
    params.require(:picture).permit(:user, :caption, :photo, :collaboration_id)
  end
end

app/views/pictures/_modals.html.erb
<!-- New Photo Modal-->
<div class="modal fade" id="newPhotoModal" tabindex="-1" aria-labelledby="newPhotoModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newPhotoModalLabel">Add a photo</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render 'new' %>
      </div>
    </div>
  </div>
</div>

<!-- Suggest Collab  Modal-->
<div class="modal fade" id="collabModal" tabindex="-1" aria-labelledby="collabModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="collabModalLabel">Collaborate</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render 'collaborations/new' %>
      </div>
    </div>
  </div>
</div>

app/views/pictures/_new.html.erb
<div class="container">
  <h1>New photo</h1>
  <%= simple_form_for(@picture) do |f| %>
    <%= f.input :photo, as: :file %>
    <% my_id = current_user.id %>
    <%= f.input :collaboration_id, label: 'Part of a collab?',
        collection: Collaboration.where(["artist1_id = ? or artist2_id = ?", my_id, my_id]).where(status: 1) %>
    <%= f.input :caption %>
    <%= f.submit "Add to my gallery", class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/pictures/_user_feed_photos.html.erb
<% pictures.take(50).shuffle.each do |pic| %>
  <div class="card-category masonry-element">
    <%= cl_image_tag pic.photo.key, style: 'height: 100%;' %>
    <div class="tags">
      <% pic.categories.each do |category| %>
        <span class="badge rounded-pill bg-light text-dark mx-1" data-tag-name="<%= category.name %>" data-action="click->search#searchByTag"><%= category.name %></span>
      <% end %>
    </div>
    <%= link_to gallery_path(pic.user.username), class: 'tag-avatar' do %>
      <%= cl_image_tag pic.user.photo.key %>
    <% end %>
  </div>
<% end %>

app/views/pictures/index.html.erb
<h1>Users</h1>

<ul><%= render @users %></ul>

app/views/pictures/new.html.erb
<div class="container">
  <%= render 'new' %>
</div>

app/views/pictures/user_feed.html.erb
<div data-controller="search">
  <div class="feeds-banner">
    <h1>Discover something new</h1>
    <%= simple_form_for :search,
                        url: root_path,
                        method: :get,
                        html: {
                          data: {
                            search_target: 'form',
                            action: 'submit->search#search'
                          }
                        } do |f| %>
      <div class="search-form-control form-group">
        <input class="form-control string required" type="text" name="query" id="search_query"
              data-search-target="input" data-action="input->search#search"/>
        <button name="button" type="submit" class="btn btn-flat">
          <i class="fas fa-search"></i>
        </button>

      </div>
    <% end %>
  </div>

  <div class="photo-feed-behavior">
    <ul data-search-target="picturesContainer" data-controller="grid">
      <%= render 'pictures/user_feed_photos', pictures: @pictures %>
    </ul>
  </div>
</div>

app/views/pictures/user_gallery.html.erb
<div data-controller="user-search">
  <div class='user-banner mb-2' style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.5)), url(https://images.unsplash.com/photo-1571085441274-292fd836e1fd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1728&q=80)">
    <div class="banner-container">
      <h1 style="margin-bottom: 0px;">
        <% if @user.photo.attached? %>
          <%= cl_image_tag @user.photo.key, class: "avatar-large" %>
        <% end %>
        <%= @user.first_name %> <%= @user.last_name %>
      </h1>
      <h3 style="margin-bottom: 0;">Bio: <%= @user.bio %></h3>
      <p style="margin-bottom: 0;">
        <%= @user_pictures.count %> photos
      </p>
      <p class="tags">
        <span class="add-photo-btn-tags selected"
              data-user-search-target="tag"
              data-action="click->user-search#allImages">
          All
        </span>
        <% @user_categories.each do |cat_name| %>
          <span class="add-photo-btn-tags"
                data-user-search-target="tag"
                data-tag-name="<%= cat_name %>"
                data-action="click->user-search#filter">
            <%= cat_name %>
          </span>
        <% end %>
      </p>
      <div class="d-flex" style="margin-left:15px;">
        <% if @user != current_user %>
          <button type="button" class="add-photo-btn-user-collab" data-bs-toggle="modal" data-bs-target="#collabModal">
            Collaborate →
          </button>
          <% end %>
        <% if @user == current_user %>
          <button type="button" class="add-photo-btn-user" data-bs-toggle="modal" data-bs-target="#newPhotoModal">
            +Add photo
          </button>
        <% else %>
          <%= link_to 'Contact → ', chatroom_path(@single_chatroom), class: "add-photo-btn-user" %>
        <% end %>
      </div>
    </div>

  </div>

  <%= render 'modals' %>

  <nav id="nav-gallery">
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <button class="nav-link active" id="nav-main-tab" data-bs-toggle="tab" data-bs-target="#nav-main" type="button" role="tab" aria-controls="nav-main" aria-selected="true">Personal gallery</button>
      <button class="nav-link" id="nav-collabs-tab" data-bs-toggle="tab" data-bs-target="#nav-collabs" type="button" role="tab" aria-controls="nav-collabs" aria-selected="false">Collabs</button>
    </div>
  </nav>


  <div class="tab-content" id="nav-tabContent">
    <!-- PERSONAL PHOTOS -->
    <div class="tab-pane fade show active" id="nav-main" role="tabpanel" aria-labelledby="nav-main-tab">
      <div class="photo-behavior" data-controller="view-photo">
        <ul>
          <% @user_pictures.each do |pic| %>
            <li class="user-pic" data-user-search-target="image"
                data-categories="<%= pic.categories.map(&:name).join(' ') %>">
              <a data-action="click->view-photo#view" data-boitier="<%= pic.boitier %>"
                      data-objectif="<%= pic.objectif %>" data-ouverture="<%= pic.ouverture %>"
                      data-tempspose="<%= pic.temps_pose %>" data-sensibilite="ISO <%= pic.sensibilite %>">
                <%= cl_image_tag pic.photo.key %>
              </a>

              <% if @user == current_user %>
                <div class="dropdown">
                  <a  type="button" class="dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i id="edit_pencil" class="fas fa-edit"></i>
                  </a>
                  <div class="dropdown-menu">
                    <%= link_to "Edit", "#", class: "dropdown-item" %>
                    <%= link_to "Delete",
                          picture_path(pic),
                          method: :delete,
                          data: { confirm: "Are you sure you want to delete this picture? This action is irreversible." },
                          class: "dropdown-item" %>
                  </div>
                </div>
              <% end %>

              <% if @user != current_user %>
                <div class="favourite" data-controller="add-fav">
                  <i class="fas fa-heart" data-add-fav-target="heart"
                   data-action="click->add-fav#like"></i>
                </div>
              <% end %>

              <div id="gallery_modal" class="modal" data-controller="modal" data-view-photo-target="modal">
                <div class="modal-dialog">
                    <div id="gallery_modal_content" class="modal-content">
                      <div class="close-btn"><a data-action="click->modal#close">X</a></div>
                      <div class="photo-modal" data-modal-target="photo">
                      </div>
                    </div>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <!-- COLLABORATION PHOTOS -->
    <div class="tab-pane fade" id="nav-collabs" role="tabpanel" aria-labelledby="nav-collabs-tab">
      <div class="photo-behavior" data-controller="view-photo">
        <ul>
          <% @user_collab_pictures.each do |pic| %>
            <li class="collab-pic" data-user-search-target="image"
                data-categories="<%= pic.categories.map(&:name).join(' ') %>">
              <a data-action="click->view-photo#view" data-boitier="<%= pic.boitier %>"
                      data-objectif="<%= pic.objectif %>" data-ouverture="<%= pic.ouverture %>"
                      data-tempspose="<%= pic.temps_pose %>" data-sensibilite="ISO <%= pic.sensibilite %>">
                <%= cl_image_tag pic.photo.key %>
              </a>
              <% collab = Collaboration.find(pic.collaboration_id) %>
              <%= link_to collab.name, collaboration_path(collab), class: 'collab-name' %>
              <%= link_to gallery_path(collab.artist1.username), class: 'collab-av1 avatar' do %>
                <%= cl_image_tag collab.artist1.photo.key, style: 'border-radius:50%;' %>
              <% end %>
              <%= link_to gallery_path(collab.artist2.username), class: 'collab-av2 avatar' do %>
                <%= cl_image_tag collab.artist2.photo.key, style: 'border-radius:50%;' %>
              <% end %>
              <div id="gallery_modal" class="modal" data-controller="modal" data-view-photo-target="modal">
                <div class="modal-dialog">
                    <div id="gallery_modal_content" class="modal-content">
                      <div class="close-btn"><a data-action="click->modal#close">X</a></div>
                      <div class="photo-modal" data-modal-target="photo">
                      </div>
                    </div>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

  </div>
</div>