config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # root to: 'pictures#user_feed'
  root to: 'pages#home'

  resources :users, only: [:index]

  resources :chatrooms, only: [:create, :show, :index] do
    resources :messages, only: :create
  end

  resources :pictures, only: [:new, :create, :destroy]
  resources :collaborations
  get '/feed', to: 'pictures#user_feed', as: "feed"
  get '/:username', to: 'pictures#user_gallery', as: "gallery"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/collaboration.rb
class Collaboration < ApplicationRecord
  belongs_to :artist1, foreign_key: :artist1_id, class_name: 'User'
  belongs_to :artist2, foreign_key: :artist2_id, class_name: 'User'
  has_many :pictures, dependent: :destroy
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  before_action :set_collab, only: [:show, :update, :destroy]

  def index
    my_id = current_user.id
    @validated_collabs = Collaboration.where(["artist1_id = ? or artist2_id = ?", my_id, my_id]).where(status: 1)
    @sent_pending = Collaboration.where(artist1: current_user).where(status: 0)
    @sent_refused = Collaboration.where(artist1: current_user).where(status: 2)
    @received_pending = Collaboration.where(artist2: current_user).where(status: 0)
    @received_refused = Collaboration.where(artist2: current_user).where(status: 2)
  end

  def new
    @collab = Collaboration.new
  end

  def create
    @collab = Collaboration.new(collab_params)
    @collab.artist1 = current_user
    @receiver = User.find_by(username: params[:artist2])
    @collab.artist2 = @receiver
    if @collab.save
      redirect_to gallery_path(@receiver.username), notice: "Collaboration request sent"
    else
      render :new
    end
  end

  def show
    @collab_pictures = Picture.where(collaboration_id: @collab.id)
    @artist1 = User.find(@collab.artist1_id)
    @artist2 = User.find(@collab.artist2_id)
    @collab_categories = []
    @collab_pictures.each do |pic|
      pic.categories.each do |category|
        @collab_categories.push(category.name)
      end
    end
    @collab_categories.uniq!
  end

  def update
    @collab.update(status: params["status"])
    respond_to do |format|
      format.html { redirect_to collaborations_path }
      format.text { redirect_to collaborations_path }
    end
  end

  def destroy
    @collab.destroy
    redirect_to collaborations_path
  end

  private

  def set_collab
    @collab = Collaboration.find(params[:id])
  end

  def collab_params
    params.require(:collaboration).permit(:name, :status, :artist1_id, :artist2_id, :description)
  end
end

app/views/collaborations/_collab_galleries.html.erb
<% @validated_collabs.reverse.each do |collab| %>
        <div class="card-collab">
          <div class="av1">
            <% if collab.artist1.photo.attached? %>
              <%= cl_image_tag collab.artist1.photo.key, class: "avatar"%>
            <% end %>
            <div class="av2">
              <% if collab.artist2.photo.attached? %>
                <%= cl_image_tag collab.artist2.photo.key, class: "avatar"%>
              <% end %>
            </div>
            <%= link_to collab.name, collaboration_path(collab), class: "collab-name h5 mx-2 my-1"%>
            <div class="collab_pic_count">
              <%= collab.pictures.count %> photos
            </div>
          </div>
          <br>

          <% if collab.pictures.count == 0 %>
            <div class="text-center">No pictures yet</div>
            <div class="text-center"><%= link_to "Start adding photos", new_picture_path, class: "btn btn-add" %></div>
          <% end %>

          <div class="collab-pictures d-flex">
            <% lastpics = collab.pictures.last(3) %>

            <% if lastpics.count == 1 %>
              <%= cl_image_tag collab.pictures[0].photo.key, height: "300", width:"100%" %>
            <% end %>

            <% if lastpics.count == 2 %>
              <%= cl_image_tag collab.pictures[0].photo.key, height: "300", width:"340" %>
              <%= cl_image_tag collab.pictures[1].photo.key, height: "300", width:"340" %>
            <% end %>

            <% if lastpics.count == 3 %>
              <%= cl_image_tag collab.pictures[0].photo.key, height: "300", width:"340" %>
                <div class="d-flex flex-column">
                  <%= cl_image_tag collab.pictures[1].photo.key, height: "150", width:"340", class: "pb-1" %>
                  <%= cl_image_tag collab.pictures[2].photo.key, height: "150", width:"340" %>
                </div>
            <% end %>

          </div>

        </div>
      <% end %>
    </div>

app/views/collaborations/_new.html.erb
<% photographer = params[:username] %>

<div class="container">
  <h3>Suggest a collab' to <%= photographer %></h3>

  <%= simple_form_for(@collab) do |f| %>
    <%= hidden_field_tag 'artist2', "#{photographer}" %>
    <%= f.input :name, label: 'Name of the collaboration' %>
    <%= f.input :description, label: "Tell #{photographer} why you want to collaborate" %>
    <%= f.submit "Suggest collab", class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/collaborations/_received.html.erb
<% if @received_pending.count == 0 %>
  <span class="no_request">No request pending</span>
<% end %>

<% @received_pending.reverse.each do |collab| %>
                <div class="card-collab-pending" data-controller="answer-collab">
                  <div class="d-flex collab-intro">
                    <%= link_to gallery_path(collab.artist1.username) do %>
                      <%= cl_image_tag collab.artist1.photo.key, class: "avatar mx-2"%>
                    <% end %>
                    <div class="sent_log">
                      <%= collab.artist1.username %> is suggesting a collab
                      <div class="sent_date">
                      <%= collab.created_at.strftime("%d/%m/%Y") %>
                      </div>
                    </div>
                  </div>
                  <div class="collab-infos mx-2 my-1">
                    <h5><%= collab.name %></h5>
                    <%= collab.description %>
                  </div>
                  <div class="collab-answer d-flex justify-content-end my-1">
                    <%= simple_form_for collab, html: {data: { answer_collab_target: "form", action: "submit->answer-collab#updatestatus"} } do |f| %>
                      <%= hidden_field_tag 'status', 1 %>
                      <%= f.submit "Accept", class: "btn btn-accept mx-1" %>
                    <% end %>
                    <%= simple_form_for collab, html: {data: { answer_collab_target: "form", action: "submit->answer-collab#updatestatus"} } do |f| %>
                      <%= hidden_field_tag 'status', 2 %>
                      <%= f.submit "Refuse", class: "btn btn-refuse mx-1" %>
                    <% end %>
                  </div>
                </div>
              <% end %>

app/views/collaborations/_refused_collabs.html.erb
<h4>Refused</h4>
            <% @received_refused.each do |collab| %>
              <%= collab.name %>
            <% end %>


<h4>Refused</h4>
            <% @sent_refused.each do |collab| %>
              <%= collab.name %>
            <% end %>

app/views/collaborations/_sent.html.erb
<% if @sent_pending.count == 0 %>
  <div class="no_request">No request sent</div>
  <%= link_to "Get inspired", feed_path, class: "btn btn-browse" %>
<% end %>

<% @sent_pending.reverse.each do |collab| %>
            <div class="card-collab-pending">
              <div class="collab-intro mx-2">
                <%= link_to gallery_path(collab.artist2.username) do %>
                  <%= cl_image_tag collab.artist2.photo.key, class: "avatar"%>
                <% end %>
                <div class="sent_log">
                  Collab request sent to <%= collab.artist2.username %>
                  <div class="sent_date">
                     <%= collab.created_at.strftime("%d/%m/%Y") %>
                  </div>
                </div>

              </div>
              <div class="collab-infos mx-2 my-1">
                <h5><%= collab.name %></h5>
                <%= collab.description %>
              </div>
              <div class="collab-answer d-flex justify-content-end mx-2">
                <%= link_to "Cancel request",
                  collaboration_path(collab),
                  class: "cancel-request",
                  method: :delete,
                  data: { confirm: "Are you sure you want to cancel this request?" } %>
              </div>
            </div>
        <% end %>

app/views/collaborations/index.html.erb
<div class="collab-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://leica-camera.com/sites/default/files/styles/hero_content_desktop/public/2022-05/Pre-Owned_Startpage_3840x1780px_Header_darker.jpg?itok=vEPC_BK_);">
    <div class="container">
      <h1>Collaborations</h1>
    </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-8">
      <h2>Galleries</h2>
      <%= render 'collab_galleries' %>

    <div class="col-4">
      <h2>Collab' requests</h2>
        <h4>Received</h4>
          <%= render 'received' %>

      <br><br>

      <h4>Sent</h4>
        <%= render 'sent' %>

    </div>
  </div>
</div>

app/views/collaborations/new.html.erb
<% photographer = params[:username] %>

<div class="container">
  <h3>Suggest a collab' to <%= photographer %></h3>
  
  <%= simple_form_for(@collab) do |f| %>
    <%= f.input :name, label: 'Name of the collaboration' %>
    <%= f.submit "Suggest collab", class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/collaborations/show.html.erb
<div data-controller="user-search" class='user-banner collab-show-banner mb-2' style="background-image: linear-gradient(rgba(0,0,0,0.0), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1533134486753-c833f0ed4866?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80)">
  <div class="banner-container">
    <div class="d-flex">
        <%= link_to gallery_path(@artist1.username), class: "collab-artist" do %>
          <%= cl_image_tag @artist1.photo.key, class: ' av1 avatar-large' %>
        <% end %>
        <%= link_to gallery_path(@artist2.username), class: "collab-artist" do %>
          <%= cl_image_tag @artist2.photo.key, class: 'av2 avatar-large' %>
        <% end %>
        <div class="collab-title">
          <h1><%= @artist1.first_name %> <%= @artist1.last_name %> X <%= @artist2.first_name %> <%= @artist2.last_name %></h1>
          <h2><%= @collab.name %></h2>
        </div>
    </div>


    <div class="collab-details">
      <h3><%= @collab.story %></h3>
      <p class="tags">
        <span class="add-photo-btn-tags selected"
              data-user-search-target="tag"
              data-action="click->user-search#allImages">
          All
        </span>
        <% @collab_categories.each do |cat_name| %>
          <span class="add-photo-btn-tags"
                data-user-search-target="tag"
                data-tag-name="<%= cat_name %>"
                data-action="click->user-search#filter">
            <%= cat_name %>
          </span>
        <% end %>
        <span><%= @collab_pictures.count %> photos</span>
      </p>
    </div>

    <% if @artist1 == current_user || @artist2 == current_user %>
      <button type="button" class="add-photo-btn-user" data-bs-toggle="modal" data-bs-target="#newPhotoModal">
        +Add photo
      </button>
    <% end %>
  </div>
</div>

<div class="photo-feed-behavior">
  <ul data-search-target="picturesContainer" data-controller="grid">
      <% @collab_pictures.each do |pic| %>
      <div class="card-category masonry-element" data-user-search-target="image">
        <%= cl_image_tag pic.photo.key, style: 'height: 100%;' %>
      </div>
    <% end %>
  </ul>
</div>